#https://github.com/pages-themes/slate
theme: jekyll-theme-slate
is_project_page: true
google_analytics:
  G-1MNZ51WDCY
  #jekyll-theme-hacker
  #baseurl: /EA_SOP_Visualization #https://stackoverflow.com/questions/16316311/github-pages-and-relative-paths
